apiVersion: apps/v1
kind: Deployment
metadata:
  name: house
  labels:
    app: house
spec:
  selector:
    matchLabels:
      app: house
  template:
    metadata:
      labels:
        app: house
    spec:
      containers:
      - name: house-client
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "120"
        image: <IMAGE_FRONTEND>
        ports:
        - containerPort: 80
      - name: house-server
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "120"
        image: <IMAGE_BACKEND>
        ports:
          - containerPort: 3000
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-host
          - name: DATABASE_NAME
            value: "house"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-auth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-auth
                key: password