apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "churrer.xyz"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: house
            port:
              number: 80