on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build client container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/house:$(echo $GITHUB_SHA | head -c7) ./client

      - name: Build server container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/house-server:$(echo $GITHUB_SHA | head -c7) ./server

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push client image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/house:$(echo $GITHUB_SHA | head -c7)

      - name: Push server image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/house-server:$(echo $GITHUB_SHA | head -c7)

      - name: Update secrets file
        run: sed -i 's|<MONGO_USERNAME>|${{ secrets.MONGO_USERNAME }}|' $GITHUB_WORKSPACE/.k8s/mongo/credentials.yaml

      - name: Update secrets file
        run: sed -i 's|<MONGO_PASSWORD>|${{ secrets.MONGO_PASSWORD }}|' $GITHUB_WORKSPACE/.k8s/mongo/credentials.yaml

      - name: Update deployment file (client image)
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<IMAGE_FRONTEND>|${{ secrets.REGISTRY_NAME }}/house:'${TAG}'|' $GITHUB_WORKSPACE/.k8s/deployment.yaml

      - name: Update deployment file (server image)
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<IMAGE_BACKEND>|${{ secrets.REGISTRY_NAME }}/house-server:'${TAG}'|' $GITHUB_WORKSPACE/.k8s/deployment.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
      
      - name: Switch namespace
        run: kubectl config set-context --current --namespace=house

      - name: Deploy mongo db
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s/mongo

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s/service.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s/deployment.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s/ingress.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/house